[build-system]
requires = ["scikit-build-core>=0.5.0", "setuptools-scm>=7", "pybind11>=2.11"]
build-backend = "scikit_build_core.build"

[project]
name = "mqt.qecc"
description = "QECC - An MQT Tool for Quantum Error Correcting Codes"
readme = "README.md"
authors = [
    { name = "Lucas Berent", email = "lucas.berent@tum.de" },
    { name = "Lukas Burgholzer", email = "lukas.burgholzer@tum.de" },
    { name = "Peter-Jan H.S. Derks", email = "peter-janderks@hotmail.com" }
]
keywords = ["MQT", "quantum-computing", "error-correction", "MaxSAT", "QLDPC"]
license = { file = "LICENSE" }

classifiers = [
    "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: C++",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Development Status :: 5 - Production/Stable",
    "Typing :: Typed",
]
requires-python = ">=3.8"
dependencies = [
    "z3-solver~=4.11.0",
    "qecsim",
    "ldpc>=0.1.50",
    "numpy",
    "qiskit-terra>=0.23.0",
    "qiskit-aer>=0.12.1",
]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest>=7.2", "pytest-console-scripts>=1.4", "pytest-mock"]
coverage = ["mqt.qecc[test]", "pytest-cov"]
docs = [
    "sphinx>=5, <7",
    "sphinx-rtd-theme",
    "sphinx-rtd-dark-mode",
    "sphinxcontrib-bibtex>=2.4.2",
    "sphinx-copybutton",
    "sphinx-hoverxref",
    "pybtex>=0.24",
    "importlib_metadata>=4.4; python_version < '3.10'",
    "ipython",
    "ipykernel",
    "nbsphinx",
    "sphinxext-opengraph",
    "qiskit-terra[visualization]",
]
visualization = ["matplotlib", "scipy"]
dev = ["mqt.qecc[coverage, docs, visualization]"]

[project.scripts]
"ecc_qiskit_wrapper" = "mqt.qecc.ecc_qiskit_wrapper:main"
"mqt.qecc.cc-decoder" = "mqt.qecc.cc_decoder.cli:cli"
"mqt.qecc.cc-decoder-plot" = "mqt.qecc.cc_decoder.plots:main"

[project.urls]
Homepage = "https://github.com/cda-tum/mqt-qecc"
Documentation = "https://github.com/cda-tum/mqt-qecc"
Issues = "https://github.com/cda-tum/mqt-qecc/issues"
Discussions = "https://github.com/cda-tum/mqt-qecc/discussions"

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "0.5.0"

# Set the target to build
cmake.targets = ["pyqecc"]

# Set required CMake and Ninja versions
cmake.minimum-version = "3.19"
ninja.minimum-version = "1.10"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"

# Explicitly set the package directory
wheel.packages = ["src/mqt"]

metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
sdist.include = ["src/mqt/qecc/_version.py"]
sdist.exclude = [
    "**/.github",
    "**/doc",
    "**/docs",
    "**/meta",
    "**/plots",
    "**/test",
    "**/tests",
    "extern/mqt-core/extern/json/include",
    "extern/mqt-core/extern/googletest",
    "extern/mqt-core/extern/boost/config/checks",
    "extern/mqt-core/extern/boost/config/tools",
    "extern/mqt-core/extern/boost/multiprecision/config",
    "extern/mqt-core/extern/boost/multiprecision/example",
    "extern/mqt-core/extern/boost/multiprecision/performance",
    "extern/mqt-core/extern/boost/multiprecision/tools"
]

[tool.scikit-build.cmake.define]
BUILD_MQT_QECC_TESTS = "OFF"
BUILD_MQT_QECC_BINDINGS = "ON"
ENABLE_IPO = "ON"


[tool.check-sdist]
sdist-only = ["src/mqt/qecc/_version.py"]
git-only = [
    "docs/*",
    "extern/*",
    "examples/*",
    "test/*",
    ".idea/*",
]


[tool.setuptools_scm]
write_to = "src/mqt/qecc/_version.py"

[tool.pytest.ini_options]
minversion = "7.2"
testpaths = ["test/python"]
addopts = ["-ra", "--strict-markers", "--strict-config", "--showlocals"]
log_cli_level = "INFO"
xfail_strict = true
filterwarnings = [
    "error",
    "ignore:pkg_resources.*:DeprecationWarning:",
    'ignore:.*qiskit.__qiskit_version__.*:DeprecationWarning:qiskit:',
]

[tool.coverage.run]
source = ["mqt.qecc"]

[tool.coverage.report]
show_missing = true
skip_empty = true
precision = 1

[tool.check-manifest]
ignore = [
    "docs/**",
    ".*",
    ".*/**",
    "noxfile.py"
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
src_paths = ["mqt/qecc", "test/python"]

[tool.mypy]
files = ["src/mqt", "test/python"]
mypy_path = ["$MYPY_CONFIG_FILE_DIR/src"]
python_version = "3.8"
strict = true
warn_unused_configs = true
check_untyped_defs = true
show_error_codes = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true
explicit_package_bases = true
pretty = true

[[tool.mypy.overrides]]
module = ["qiskit.*", "qiskit_aer.*", "qecsim.*" , "matplotlib.*", "scipy.*", "ldpc.*", "pytest_console_scripts.*", "z3.*"]
ignore_missing_imports = true

[tool.ruff]
select = [
    "E", "F", "W", # flake8
    "A", # flake8-builtins
    "ANN", # flake8-annotations
    "ARG", # flake8-unused-arguments
    "B", "B904", # flake8-bugbear
    "C4", # flake8-comprehensions
    "D", # pydocstyle
    "EM", # flake8-errmsg
    "EXE", # flake8-executable
    "I", # isort
    "ICN", # flake8-import-conventions
    "ISC", # flake8-implicit-str-concat
    "N", # flake8-naming
    "PGH", # pygrep-hooks
    "PIE", # flake8-pie
    "PL", # pylint
    "PT", # flake8-pytest-style
    "PTH", # flake8-use-pathlib
    "PYI", # flake8-pyi
    "Q", # flake8-quotes
    "RET", # flake8-return
    "RSE", # flake8-raise
    "RUF", # Ruff-specific
    "SLF", # flake8-self
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "TID", # flake8-tidy-imports
    "TRY", # tryceratops
    "UP", # pyupgrade
    "YTT", # flake8-2020
]
ignore = [
    "ANN101", # Missing type annotation for self in method
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "E501", # Line too long (Black is enough)
    "PLR2004", # Magic values
    "PLR0913", # Too many arguments
]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

line-length = 120
[tool.ruff.per-file-ignores]
"*.pyi" = [
    "D", # pydocstyle
]
